package org.woofdb.core.models;

public enum StatementType {
    STATEMENT_USE,
    STATEMENT_INSERT,
    STATEMENT_SELECT,
    STATEMENT_CREATE,
    STATEMENT_UPDATE,
    STATEMENT_DROP,
    STATEMENT_ROLLBACK,
    STATEMENT_START_TRANSACTION,
    STATEMENT_SHOW,
    STATEMENT_COMMIT;
}
